<div style="background-color: #e0f7fa; font-family: Arial, sans-serif; padding: 20px; border-radius: 10px; max-width: 95%; border-bottom: 2px solid #ccc; text-align: center;">

  <h1 style="font-size: 2.5em; color: #004d40; margin-bottom: 10px;">StatisticalWeather</h1>
  <h3 style="color: #004d40; margin-top: 0;">Projet d'analyse de données</h3>

  <p>
    Réalisé par <strong>Christophe Debons</strong> et <strong>Guillaume Leibzig</strong><br>
    Sous la supervision de <strong>Prof. Benoît Le Cannellec</strong><br>
    <em>Haute École ARC – Neuchâtel</em> | 2025
  </p>

  <p style="font-size: 0.9em; color: #004d40; margin-top: 30px;">Tous droits réservés</p>

  <img src="./data/Haute-Ecole-Arc/ARC_RGB_300dpi_Logo.jpg"
       alt="Logo HE-Arc" width="180" style="margin-top: 5px;" />

</div>

<div style="background-color: #e0f7fa; color: #004d40; padding: 25px; border-radius: 10px; max-width: 95%; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="color: #9b4d00;">🧩 Table des matières</h2>
  <ol style="line-height: 1.8;">
    <li><strong>Introduction</strong></li>
    <li><strong>Mode d'emploi</strong></li>
    <li><strong>Provenance et types des données</strong></li>
    <li><strong>Traitements et manipulations</strong></li>
    <li><strong>Affichage et Widgets</strong></li>
    <li><strong>Problèmes rencontrés</strong></li>
    <li><strong>Bugs connus</strong></li>
    <li><strong>Conclusion</strong></li>
  </ol>

  <h2 style="color: #9b4d00;">📍 Introduction</h2>

  <p>
    Chacun des deux auteurs de ce projet revendique de résider dans la plus belle région de Suisse.
    L'un est un Valaisan convaincu, l'autre un Fribourgeois qui ne l'est pas moins.
    Pour trancher objectivement, nous avons décidé de mettre de côté les considérations subjectives
    et de procéder à une analyse des données météorologiques fournies par <strong>MeteoSuisse</strong>.
  </p>

  <p>
    L’objectif ? Visualiser sur une carte quelles régions (stations de mesure) bénéficient :
    <ul style="margin-left: 20px;">
      <li>☀️ d’un ensoleillement relatif plus élevé,</li>
      <li>🌡️ de températures moyennes mensuelles plus clémentes,</li>
      <li>🌧️ de précipitations moindres.</li>
    </ul>
  </p>

  <p>
    Une carte interactive permet de filtrer les stations par tranche d'altitude,
    rendant la comparaison plus équitable. Enfin, un score de 1 à 10 a été calculé
    pour chaque station afin d’identifier la région bénéficiant du climat le plus favorable.
  </p>

  <div style="display: flex; flex-direction: column; align-items: center; gap: 20px; margin-top: 30px;">
    <img src="./data/Screenshots/Carte_interractive.jpg" alt="Aperçu de la carte interactive"
         title="Aperçu de la carte interactive" style="width: 80%; border-radius: 8px; box-shadow: 2px 2px 8px #ccc;" />
    <p>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 20px; margin-top: 30px;">
    <img src="./data/Screenshots/Score.jpg" alt="Aperçu du score" 
         title="Aperçu de la représentation du score" style="width: 80%; border-radius: 8px; box-shadow: 2px 2px 8px #ccc;" />
  </div>

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

<h2 style="color: #9b4d00;">🛠️ Mode d'emploi du Notebook</h2>

  <li>
  <strong>Créez et activez un environnement virtuel</strong> :

  <p><em>Windows :</em></p>
  <div style="background-color: #e0f2f1; padding: 10px; border-radius: 5px; font-family: monospace; text-align: left;">
    python -m venv .venv<br>
    .venv\Scripts\activate<br>
    pip install --upgrade pip<br>
    pip install -r requirements.txt
  </div>

  <p><em>Linux/macOS :</em></p>
  <div style="background-color: #e0f2f1; padding: 10px; border-radius: 5px; font-family: monospace; text-align: left;">
    python3 -m venv .venv<br>
    source .venv/bin/activate<br>
    pip install --upgrade pip<br>
    pip install -r requirements.txt
  </div>
</li>

<li>
  <strong>Lancez Jupyter Notebook</strong> :
  <div style="background-color: #e0f2f1; padding: 10px;


<li>
  <strong>Lancez Jupyter Notebook</strong> :
  <div style="background-color: #e0f2f1; padding: 10px; border-radius: 5px; font-family: monospace;">
    jupyter notebook
  </div>
</li>

<li>
  <strong>Ouvrez</strong> le fichier <code>StatisticalWeather.ipynb</code> et exécutez les cellules.
</li>

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="margin-top: 0;">📁 Provenance des données</h2>

  <p>Depuis mai 2025, <strong>MétéoSuisse</strong> (<a href="https://www.meteosuisse.admin.ch/services-et-publications/service/open-data.html" target="_blank">OpenData MétéoSuisse</a>)
  rend ses données accessibles en tant qu’OGD (Open Government Data). Les données sont continuellement mises à jour, téléchargeables gratuitement, et leur usage est libre.</p>

  <p>Des données sont disponibles depuis <strong>1901</strong>. MétéoSuisse gère <strong>158 sites de mesures</strong> répartis sur toute la Suisse. Évidemment, le type de données disponibles varie selon les stations et les époques. Un standard fiable dans la collecte des données n’est atteint qu’à partir des années 1960, ce qui motive notre décision de ne travailler qu’avec des données postérieures à cette période.</p>

  <h3>🗂️ Structure des données</h3>

  <p>Les données sont réparties dans plusieurs fichiers CSV :</p>

  <ul style="margin-left: 20px;">
    <li><strong>Un fichier par station</strong>, contenant :
      <ul>
        <li>📅 La date de chaque enregistrement</li>
        <li>🔢 Le code du type de valeur</li>
        <li>📈 Toutes les valeurs enregistrées par la station</li>
      </ul>
    </li>
    <li><strong>Un fichier <code>columns_identifier</code></strong>, avec :
      <ul>
        <li>🧪 Le nom de la mesure</li>
        <li>📐 Ses caractéristiques</li>
        <li>💾 Le format des données</li>
      </ul>
    </li>
    <li><strong>Un fichier <code>station_identifier</code></strong>, qui décrit chaque station :
      <ul>
        <li>🏷️ Son abréviation</li>
        <li>📍 Le nom de la localité</li>
        <li>📏 L’altitude</li>
        <li>🌍 Les coordonnées GPS</li>
      </ul>
    </li>
  </ul>

  <p>Ces fichiers ont été téléchargés directement depuis le site mentionné ci-dessus.</p>

  <p><strong>Notre script</strong> permet d’exploiter ces fichiers pour générer le fichier <code>dataWeather</code>. Celui-ci est trop volumineux pour être inclus dans notre dépôt GitHub, et doit donc être généré localement par l'utilisateur. Cette opération prend moins de 5 minutes.</p>

  <h2>🔧 Traitements et manipulations</h2>

  <ul style="margin-left: 20px;">
    <li>📦 Le processus commence par l’importation des dépendances nécessaires.</li>
    <li>🛠️ Les données de chaque fichier station sont ensuite agrégées dans <code>dataWeather</code>.</li>
    <li>📅 Ce fichier contient une moyenne quotidienne des valeurs, depuis 1901, selon les capteurs disponibles dans chaque station.</li>
    <li>⚠️ Comme indiqué, les données antérieures à 1960 sont incomplètes et souvent non exploitables.</li>
  </ul>

</div>

In [1]:
import pandas as pd

import matplotlib.pyplot as plt

import os
from datetime import datetime

In [2]:
df_list = []
current_directory = os.getcwd()

OUTPUT_CSV = "\\data\\dataWeather.csv"

folder_path = current_directory + "\\data\\dataTemp\\month"
csv_files = os.listdir(folder_path)
#we decided to ignore files under 1000 kbit, those may not contain enough data
pathFile = 'data/dataWeather.csv'
if not os.path.isfile(pathFile):
    for file in csv_files:
        try:
            file_path = folder_path + '\\' + file
            # Get the file size in kbytes
            file_size = os.path.getsize(file_path) / 1024

            if file_size > 1000:
                df = pd.read_csv(folder_path + '\\' + file)
                df_list.append(df)

        except Exception as e:
            print(f"⚠️ Erreur de lecture {file} : {e}")

    #concatenate the data (missing columns are treated)
    if df_list:
        df_final = pd.concat(df_list, ignore_index=True, sort=False)
        df_final.to_csv(current_directory + OUTPUT_CSV, index=False)
        print(f"✅ Fichier final enregistré sous {OUTPUT_CSV}")

<div style="background-color: #e0f7fa; color: #004d40; padding: 15px; max-width: 95%; border-radius: 8px; font-family: Arial, sans-serif;">
  <p><strong>–</strong> Nous ouvrons ensuite le fichier que nous venons de créer en lui indiquant le type de séparateur utilisé, pour créer un DataFrame nommé <code>dataWeather</code>.</p>
  <p><strong>–</strong> Nous affichons les dimensions du DataFrame ainsi que son apparence.</p>
</div>

In [3]:
dataWeather =  pd.read_csv('data/dataWeather.csv', sep=';')


print(f"Dimension des données: {dataWeather.shape}")

dataWeather.head()

Dimension des données: (4645786, 37)

,station_abbr,reference_timestamp,tre200d0,tre200dx,tre200dn,tre005d0,tre005dx,tre005dn,ure200d0,pva200d0,...,olo000d0,osr000d0,ods000d0,sre000d0,sremaxdv,erefaod0,xcd000d0,dkl010d0,xno000d0,xno012d0
0,ABO,01.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABO,02.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABO,03.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABO,04.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABO,05.01.1901 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div style="background-color: #e0f7fa; color: #004d40; padding: 15px; max-width: 95%; border-radius: 8px; font-family: Arial, sans-serif;">
  <p><strong>–</strong> Nous ouvrons le fichier <code>columns_identifier</code> et <code>station_identifier</code> pour en créer des Dataframe. Ceux-ci nous seront utiles pour la correspondance des noms de colonnes, ainsi que l'emplacement où les valeurs ont été recueillies.</p>
  <p><strong>–</strong> Nous les affichons pour avoir une idée de son apparence.</p>
</div>

In [4]:
columns_identifier = pd.read_csv('data/columns_identifier.csv', sep=';', encoding="latin1")

columns_identifier.head()

,parameter_shortname,parameter_description_de,parameter_description_fr,parameter_description_it,parameter_description_en,parameter_group_de,parameter_group_fr,parameter_group_it,parameter_group_en,parameter_granularity,parameter_decimals,parameter_datatype,parameter_unit
0,dkl010d0,Windrichtung; Tagesmittel,Direction du vent; moyenne journalière,Direzione del vento; media giornaliera,Wind direction; daily mean,Wind,vent,vento,wind,D,0,Integer,°
1,dkl010h0,Windrichtung; Stundenmittel,Direction du vent; moyenne horaire,Direzione del vento; media oraria,Wind direction; hourly mean,Wind,vent,vento,wind,H,0,Integer,°
2,dkl010z0,Windrichtung; Zehnminutenmittel,Direction du vent; moyenne sur 10 minutes,Direzione del vento; media su 10',Wind direction; ten minutes mean,Wind,vent,vento,wind,T,0,Integer,°
3,erefaod0,Referenzverdunstung nach FAO; Tagessumme,Évaporation de réference de FAO; somme journal...,Evaporazione referenze di FAO; somma giornaliera,Reference evaporation from FAO; daily total,Verdunstung,évaporation,evaporazione,evaporation,D,1,Float,mm/d
4,erefaoh0,Referenzverdunstung nach FAO; Stundensumme,Évaporation de réference de FAO; somme horaire,Evaporazione referenze di FAO; somma oraria,Reference evaporation from FAO; hourly total,Verdunstung,évaporation,evaporazione,evaporation,H,3,Float,mm/h

<div style="background-color: #e0f7fa; color: #004d40; padding: 15px; max-width: 95%; border-radius: 8px; font-family: Arial, sans-serif;">
  <p><strong>–</strong> Nous continuons avec l'ouverture du fichier <code>station_identifier</code>. Nous créons également un Dataframe qui sera utilisé par la suite.</p>
  <p><strong>–</strong> Nous affichons son apparence</p>
</div>

In [5]:
station_identifier = pd.read_csv('data/station_identifier.csv', sep=';', encoding="latin1")

station_identifier.head()

,station_abbr,station_name,station_canton,station_wigos_id,station_type_de,station_type_fr,station_type_it,station_type_en,station_dataowner,station_data_since,...,station_coordinates_wgs84_lat,station_coordinates_wgs84_lon,station_exposition_de,station_exposition_fr,station_exposition_it,station_exposition_en,station_url_de,station_url_fr,station_url_it,station_url_en
0,ABO,Adelboden,BE,0-20000-0-06735,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,"MeteoSchweiz, SLF",01.01.1901,...,46.491703,7.560703,Südosthang,Versant sud-est,Versante sud-orientale,south-eastern oriented slope,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
1,AEG,Oberägeri,ZG,0-20000-0-06676,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.02.1993,...,47.133636,8.608206,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
2,AIG,Aigle,VD,0-20000-0-06712,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1961,...,46.326647,6.924472,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
3,ALT,Altdorf,UR,0-20000-0-06672,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1864,...,46.887069,8.621894,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
4,AND,Andeer,GR,0-20000-0-06787,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1901,...,46.610139,9.431981,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="margin-top: 0;">Après l'analyse du type de données dont nous disposons, nous avons décidé de ne garder que :</h2>

  <ul style="margin-left: 20px;">
    <li><code>station_abbr</code> : information de base sur l'endroit où la station de mesure se trouve</li>
    <li><code>station_name</code> : information de base sur l'endroit où la station de mesure se trouve</li>
    <li><code>station_height_masl</code> : information sur la hauteur à laquelle la station de mesure se trouve </li>
    <li><code>station_coordinates_wgs84_lat</code> : coordonnées GPS de la latitude au format wgs84</li>
    <li><code>station_coordinates_wgs84_lon</code> : coordonnées GPS de la longitude au format wgs84</li>
    <li><code>reference_time</code> : date et heure à laquelle la mesure a été effectuée</li>
    <li><strong>Température de l'air</strong> à 2 m du sol/ moyenne journalière <code>[tre200d0]</code></li>
    <li><strong>Vitesse du vent</strong> scalaire/ moyenne journalière en m/s  <code>[fkl010d0]</code></li>
    <li><strong>Précipitations</strong> / somme journalière 6 UTC - 6 UTC du jour suivant <code>[rre150d0]</code></li>
    <li><strong>Auteur de neige</strong> (mesurée automatiquement) / mesure matinale de 6 UTC <code>[htoautd0]</code></li>
    <li><strong>Durée d'ensoleillement</strong> / relativement à la somme journalière maximale possible <code>[sremaxdv]</code></li>
  </ul>

 <p>Le code suivant effectue les manipulations pour supprimer les colonnes ne figurant pas sur la liste à garder.</p>
    <p>Nous décidons de ne pas remplacer les codes par des noms plus faciles à comprendre, car nous perderions des informations complémentaires. Nous récupérerons les identifiants directement sur le Dataframe <code>columns_identifier</code></p>
</div>

In [6]:
columns_list = ['station_abbr','reference_timestamp','tre200d0','fkl010d0','rre150d0', 'htoautd0', 'sremaxdv']

complete_list = list(columns_identifier['parameter_shortname'])

column_names = dataWeather.columns.tolist()

dif_list = list(set(column_names) ^ set(columns_list))

dataWeather_select = dataWeather.drop(columns=dif_list, axis=1)

dataWeather_select.head()

,station_abbr,reference_timestamp,tre200d0,fkl010d0,rre150d0,htoautd0,sremaxdv
0,ABO,01.01.1901 00:00,NaN,NaN,0.6,NaN,NaN
1,ABO,02.01.1901 00:00,NaN,NaN,1.8,NaN,NaN
2,ABO,03.01.1901 00:00,NaN,NaN,0.2,NaN,NaN
3,ABO,04.01.1901 00:00,NaN,NaN,0.0,NaN,NaN
4,ABO,05.01.1901 00:00,NaN,NaN,0.0,NaN,NaN

<div style="background-color: #e0f7fa; color: #004d40; padding: 15px; max-width: 95%; border-radius: 8px; font-family: Arial, sans-serif;">
  <p><strong>–</strong> L'opération suivante consiste à changer le format de la date et à ajouter une cologne mois et année, qui nous servira pour les calculs ultérieurs</p>
</div>

In [7]:
dataWeather_select['reference_timestamp'] = pd.to_datetime(dataWeather_select['reference_timestamp'], format='%d.%m.%Y %H:%M')
dataWeather_select['year'] = dataWeather_select['reference_timestamp'].dt.year
dataWeather_select['month'] = dataWeather_select['reference_timestamp'].dt.month
dataWeather_select.head()

,station_abbr,reference_timestamp,tre200d0,fkl010d0,rre150d0,htoautd0,sremaxdv,year,month
0,ABO,1901-01-01,NaN,NaN,0.6,NaN,NaN,1901,1
1,ABO,1901-01-02,NaN,NaN,1.8,NaN,NaN,1901,1
2,ABO,1901-01-03,NaN,NaN,0.2,NaN,NaN,1901,1
3,ABO,1901-01-04,NaN,NaN,0.0,NaN,NaN,1901,1
4,ABO,1901-01-05,NaN,NaN,0.0,NaN,NaN,1901,1

<div style="background-color: #e0f7fa; color: #004d40; padding: 15px;  max-width: 95%; border-radius: 8px; font-family: Arial, sans-serif;">
  <p><strong>–</strong> Nous créons un nouveau Dataframe <code>dataWeather_select</code> dont le contenu est amputé des lignes contenant les valeurs antérieures à 1960</p>
</div>

In [8]:
year_selected = 1960

dataWeather_select = dataWeather_select[dataWeather_select['reference_timestamp'].dt.year >= year_selected]
dataWeather_select.head()

,station_abbr,reference_timestamp,tre200d0,fkl010d0,rre150d0,htoautd0,sremaxdv,year,month
21458,ABO,1960-01-01,2.2,NaN,0.0,NaN,NaN,1960,1
21459,ABO,1960-01-02,1.5,NaN,15.2,NaN,NaN,1960,1
21460,ABO,1960-01-03,3.1,NaN,8.0,NaN,NaN,1960,1
21461,ABO,1960-01-04,0.1,NaN,0.0,NaN,NaN,1960,1
21462,ABO,1960-01-05,2.3,NaN,0.9,NaN,NaN,1960,1

<div style="background-color: #e0f7fa; color: #004d40; padding: 15px; max-width: 95%; border-radius: 8px; font-family: Arial, sans-serif;">
  <p><strong>–</strong> L'étape suivant calcule la moyenne,  l'écart type, et le nombre d’observations, dont le total est la somme par année et par mois</p>
</div>

In [9]:
# list of numeric rows, except those used by "groupby"
columns_to_aggregate = dataWeather_select.select_dtypes(include='number').columns.difference(['station_abbr', 'year', 'month'])

# Multiplication for each row
dataWeather_msc = dataWeather_select.groupby(['station_abbr', 'year', 'month'])[columns_to_aggregate].agg(['mean', 'std', 'count']).reset_index()

# Modification of the name for a better reading
dataWeather_msc.columns = ['_'.join(col).strip('_') if isinstance(col, tuple) else col for col in dataWeather_msc.columns]

pd.set_option("display.max_columns", 114)

dataWeather_msc.shape
dataWeather_msc.head()

,station_abbr,year,month,fkl010d0_mean,fkl010d0_std,fkl010d0_count,htoautd0_mean,htoautd0_std,htoautd0_count,rre150d0_mean,rre150d0_std,rre150d0_count,sremaxdv_mean,sremaxdv_std,sremaxdv_count,tre200d0_mean,tre200d0_std,tre200d0_count
0,ABO,1960,1,NaN,NaN,0,NaN,NaN,0,2.200000,3.759876,31,NaN,NaN,0,-2.977419,6.304692,31
1,ABO,1960,2,NaN,NaN,0,NaN,NaN,0,3.344828,7.226518,29,NaN,NaN,0,0.265517,4.110377,29
2,ABO,1960,3,NaN,NaN,0,NaN,NaN,0,3.167742,6.800803,31,NaN,NaN,0,2.100000,2.266716,31
3,ABO,1960,4,NaN,NaN,0,NaN,NaN,0,1.980000,3.196377,30,NaN,NaN,0,3.993333,3.087900,30
4,ABO,1960,5,NaN,NaN,0,NaN,NaN,0,3.222581,5.937492,31,NaN,NaN,0,10.029032,3.071720,31

In [10]:
# 1. Row identification
mean_cols = [col for col in dataWeather_msc.columns if col.endswith('_mean')]
std_cols = [col.replace('_mean', '_std') for col in mean_cols]
count_cols = [col.replace('_mean', '_count') for col in mean_cols]

# 2. Grouping station & month 
grouped_means = dataWeather_msc.groupby(['station_abbr', 'month'])[mean_cols].mean()
grouped_stds = dataWeather_msc.groupby(['station_abbr', 'month'])[std_cols].mean()
grouped_counts = dataWeather_msc.groupby(['station_abbr', 'month'])[count_cols].sum()

# 3. Merging all the 3 sub_tables
dataWeather_month = pd.concat([grouped_means, grouped_stds, grouped_counts], axis=1).reset_index()

# Display
dataWeather_month.head()

,station_abbr,month,fkl010d0_mean,htoautd0_mean,rre150d0_mean,sremaxdv_mean,tre200d0_mean,fkl010d0_std,htoautd0_std,rre150d0_std,sremaxdv_std,tre200d0_std,fkl010d0_count,htoautd0_count,rre150d0_count,sremaxdv_count,tre200d0_count
0,ABO,1,1.390979,16.542316,2.900447,46.505562,-1.577965,1.188149,9.576727,5.182609,40.312733,4.056368,1829,458,2015,1798,2015
1,ABO,2,1.495592,22.026638,2.940983,48.361368,-1.106175,1.075535,7.529787,5.557565,40.184200,3.849922,1667,414,1837,1639,1837
2,ABO,3,1.612411,8.586499,2.982084,46.932703,1.355087,1.056990,11.860402,5.173191,38.504304,3.823292,1829,458,2015,1798,2015
3,ABO,4,1.619605,0.590868,3.062410,43.836207,4.492051,0.776551,3.361567,5.162913,35.665133,3.896143,1770,440,1950,1740,1950
4,ABO,5,1.591799,-0.028796,4.036725,40.978309,8.781290,0.650226,0.880330,6.379034,33.371711,3.543397,1829,448,2015,1798,2015

<div style="background-color: #e0f7fa; color: #004d40; padding: 15px; max-width: 95%; border-radius: 8px; font-family: Arial, sans-serif;">
  <p><strong>–</strong> On procède au calcul de la moyenne par année pour l'affichage graphique</p>
</div>

In [11]:
# 1. Identifie les colonnes
mean_cols = [col for col in dataWeather_msc.columns if col.endswith('_mean')]
std_cols = [col for col in dataWeather_msc.columns if col.endswith('_std')]
count_cols = [col for col in dataWeather_msc.columns if col.endswith('_count')]

# 2. Grouper par station + mois
grouped_means = dataWeather_msc.groupby(['station_abbr', 'year'])[mean_cols].mean()
grouped_stds = dataWeather_msc.groupby(['station_abbr', 'year'])[std_cols].mean()
grouped_counts = dataWeather_msc.groupby(['station_abbr', 'year'])[count_cols].sum()

# 3. Fusionner les trois sous-tables
dataWeather_year = pd.concat([grouped_means, grouped_stds, grouped_counts], axis=1).reset_index()

# Affichage
dataWeather_year.head()

,station_abbr,year,fkl010d0_mean,htoautd0_mean,rre150d0_mean,sremaxdv_mean,tre200d0_mean,fkl010d0_std,htoautd0_std,rre150d0_std,sremaxdv_std,tre200d0_std,fkl010d0_count,htoautd0_count,rre150d0_count,sremaxdv_count,tre200d0_count
0,ABO,1960,NaN,NaN,3.840931,NaN,5.564617,NaN,NaN,6.256380,NaN,3.228974,0,0,366,0,366
1,ABO,1961,NaN,NaN,3.575474,NaN,6.581331,NaN,NaN,6.539303,NaN,3.312089,0,0,365,0,365
2,ABO,1962,NaN,NaN,3.398248,NaN,4.766860,NaN,NaN,6.172590,NaN,4.220100,0,0,365,0,365
3,ABO,1963,NaN,NaN,3.155425,NaN,4.740338,NaN,NaN,5.329043,NaN,3.810315,0,0,365,0,365
4,ABO,1964,NaN,NaN,2.911064,NaN,5.765451,NaN,NaN,5.414135,NaN,3.310515,0,0,366,0,366

  <div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="margin-top: 0;">Après l'analyse du type de données dont nous disposons, nous avons décidé de ne garder que :</h2>

  <ul style="margin-left: 20px;">
    <li><code>station_abbr</code></li>
    <li><code>station_name</code></li>
    <li><code>year</code></li>
    <li><code>month</code></li>
    <li><code>station_height_masl</code></li>
    <li><code>station_coordinates_wgs84_lat</code></li>
    <li><code>station_coordinates_wgs84_lon</code></li>
    <li><code>reference_timestamp</code></li>
    <li><code>Température de l'air</code> Variable ==> base: <code>[tre200d0]</code>; moyenne: <code>[tre200d0_mean]</code>; 
    écart type: <code>[tre200d0_std]</code>; nombre de valeur: <code>[tre200d0_count]</code></li>
    <li><code>Vitesse du vent</code> scalaire / moyenne journalière en m/s;  Variable ==> base: <code>[fkl010d0]</code>; moyenne: <code>[fkl010d0_mean]</code>; 
    écart type: <code>[fkl010d0_std]</code>; nombre de valeur: <code>[fkl010d0_count]</code></li>
    <li><code>Précipitations</code> / somme journalière 6 UTC du jour suivant; Variable ==> base: <code>[rre150d0]</code>; moyenne: <code>[rre150d0_mean]</code>; 
    écart type: <code>[rre150d0_std]</code>; nombre de valeur: <code>[rre150d0_count]</code></li>
    <li><code>Auteur de neige</code> (mesurée automatiquement) / mesure matinale de 6 UTC; Variable ==> base: <code>[htoautd0]</code>; moyenne: <code>[htoautd0_mean]</code>; 
    écart type: <code>[htoautd0_std]</code>; nombre de valeur: <code>[htoautd0_count]</code></li>
    <li><code>Durée d'ensoleillement</code> / relative à la somme maximale possible; Variable ==> base: <code>[sremaxdv]</code>; moyenne: <code>[sremaxdv_mean]</code>; 
    écart type: <code>[sremaxdv_std]</code>; nombre de valeur: <code>[sremaxdv_count]</code></li>
  </ul>
  <p><strong>–</strong> Outils pour la récupération des données sur les tableaux</p>
</div>

In [12]:
import folium
from IPython.display import display, clear_output
from ipywidgets import widgets
import matplotlib.cm as cm
import matplotlib.colors as colors
from matplotlib.pylab import norm
import numpy as np
from folium import Popup
from branca.element import IFrame

In [13]:
# Return unit next line
def value_unit(param_id):
    result = columns_identifier.loc[
        columns_identifier['parameter_shortname'] == param_id, 'parameter_unit'
    ]

    return result.values[0] if not result.empty else None

# Return row's definition regarding it's ID 
def columnDefinition(param_id, language='fr'):
    lang_map = {
        'fr': 'parameter_description_fr',
        'en': 'parameter_description_en',
        'de': 'parameter_description_de',
        'it': 'parameter_description_it'
    }
    col = lang_map.get(language, 'parameter_description_en')

    result = columns_identifier.loc[
        columns_identifier['parameter_shortname'] == param_id, col
    ]

    return result.values[0] if not result.empty else None


# Return the ID regarding row's definition
def columnId(description, language='fr'):
    lang_map = {
        'fr': 'parameter_description_fr',
        'en': 'parameter_description_en',
        'de': 'parameter_description_de',
        'it': 'parameter_description_it'
    }
    col = lang_map.get(language, 'parameter_description_en')

    matches = columns_identifier[
        columns_identifier[col].str.contains(description, case=False, na=False, regex=False)
    ]

    if matches.empty:
        return None 

    return matches.iloc[0]['parameter_shortname']

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="margin-top: 0;">📊 Widgets et Cartes</h2>

In [14]:
months_labels = [
    ("Janvier", 1), ("Février", 2), ("Mars", 3), ("Avril", 4),
    ("Mai", 5), ("Juin", 6), ("Juillet", 7), ("Août", 8),
    ("Septembre", 9), ("Octobre", 10), ("Novembre", 11), ("Décembre", 12)
]

colormaps_personnalisees = {
    'tre200d0': 'coolwarm',     # Température de l'air à 2 m du sol/ moyenne journalière
    'sremaxdv': 'YlOrBr',       # Durée d'ensoleillement/ relativement à la somme journalière maximale possible
    'rre150d0': 'PuBuGn',       # Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant
    'htoautd0': 'Oranges',      # Hauteur de neige (mesurée automatiquement) / mesure matinale de 6 UTC
    'fkl010d0': 'Greys'         # Vitesse du vent scalaire/ moyenne journalière en m/s 
    
}

language = 'fr'

# Widgets building
slider_altitude = widgets.IntRangeSlider(value = [400, 4000], min=400, max=4000, step=50, description='Altitude ≥', continous_update = False)
dropdown = widgets.Dropdown(options=months_labels, value=1, description='Mois :')
colorbar_checkbox = widgets.Checkbox(value=False, description='Afficher la légende', disabled=False)

variable_available = [columnDefinition(col.replace('_mean', ''), language)  for col in dataWeather_year.columns if col.endswith('_mean')]

data_selection = widgets.Dropdown(options=variable_available, description="Variable :")


def update_map(altitude_range, data_selection, month, colorbar_checkbox):

    month_name = months_labels[month - 1][0]

    alt_min, alt_max = altitude_range

    df_month = dataWeather_month[dataWeather_month['month'] == month].copy()
    
    if df_month.empty:
        print("Aucune donnée pour ce mois.")
        return
    
    data_id = columnId(data_selection, language)

    val_mean = f"{data_id}_mean"
    val_count = f"{data_id}_count"
    #val_std = f"{data_selection}_std"

    # fetching the unit
    try:
        unit = columns_identifier.loc[
            columns_identifier['parameter_shortname'] == data_id, 'parameter_unit'
        ].values[0]
    except IndexError:
        unit = ""  # empty value if value not found

    stations_valides = df_month[
        (df_month[val_count] >= 300) & 
        (~df_month[val_mean].isna())
        ].copy()

    stations_valides = stations_valides.merge(
            station_identifier[['station_abbr', 'station_name', 'station_height_masl']],
            on='station_abbr',
            how='left')
    stations_valides = stations_valides[
    stations_valides['station_height_masl'].between(alt_min, alt_max)
    ]
    # Map's dynamic color choice 
    cmap_name = colormaps_personnalisees.get(data_id, 'viridis')
    cmap = plt.get_cmap(cmap_name)

    # Color norming
    norm = colors.Normalize(vmin=stations_valides[val_mean].min(), vmax=stations_valides[val_mean].max())

    folium_map = folium.Map(location=[46.8, 8.3], zoom_start=8, width='80%', height='80%')
    popup = folium.Popup("Contenu du popup", max_width=800)


    # Labels building
    for _, station in station_identifier.iterrows():
        if not alt_min <= station['station_height_masl'] <= alt_max:
            continue

        station_abbr = station['station_abbr']
        row = df_month[df_month['station_abbr'] == station_abbr]

        if row.empty:
            continue

        value = row.iloc[0][val_mean]
        count = row.iloc[0].get(val_count, 1)
        
        if count < 300 or pd.isna(value):
            continue  # Ignored if data not sufficient for a station


        radius = max(4, min(8, np.sqrt(count)))
        color = colors.to_hex(cmap(norm(value)))

        # 🧾 Designed popup 
        html_popup = f"""
        <div style='font-family: Arial; font-size: 13px;'>
            <b style='font-size: 15px;'>{station['station_name']}</b><br>
            🏔️ Altitude : {station['station_height_masl']} m<br>
            📈 Valeur : {value:.2f} {unit}<br>
            📊 Observation{'s' if count > 1 else ''} : {count}
        </div>
        """
        iframe = IFrame(html=html_popup, width=200, height=100)
        popup = Popup(iframe, max_width=200)

        folium.CircleMarker(
            location=[
                station['station_coordinates_wgs84_lat'],
                station['station_coordinates_wgs84_lon']
            ],
            radius=radius,
            color=color,
            fill=True,
            fill_opacity=0.8,
            popup=popup
        ).add_to(folium_map)

    # Map's legend
    if colorbar_checkbox:
        vmin = stations_valides[val_mean].min()
        vmax = stations_valides[val_mean].max()
        vavg = stations_valides[val_mean].mean()


        color_min = colors.to_hex(cmap(norm(vmin)))
        color_avg = colors.to_hex(cmap(norm(vavg)))
        color_max = colors.to_hex(cmap(norm(vmax)))

        if not stations_valides.empty:      
            station_min = stations_valides.loc[stations_valides[val_mean].idxmin(), 'station_name']
            station_max = stations_valides.loc[stations_valides[val_mean].idxmax(), 'station_name']

            legend_html = f"""
            <div style="
                position: fixed;
                bottom: 50px;
                left: 50px;
                width: 450px;
                height: 170px;
                background-color: white;
                border:2px solid grey;
                z-index:9999;
                font-size:14px;
                padding: 10px;
                font-family: Arial, sans-serif;
            ">
            <b>{data_selection} – {month_name}</b><br><br>
            <span style="display:inline-block; width: 20px; height: 10px; background:{color_min}; border-radius: 2px;"></span>
            Min : {vmin:.2f} {unit} – <em>{station_min}</em><br>
            <span style="display:inline-block; width: 20px; height: 10px; background:{color_avg}; border-radius: 2px;"></span>
            Moyenne : {vavg:.2f} {unit}<br>
            <span style="display:inline-block; width: 20px; height: 10px; background:{color_max}; border-radius: 2px;"></span>
            Max : {vmax:.2f} {unit} – <em>{station_max}</em><br>
            </div>
            """

            folium_map.get_root().html.add_child(folium.Element(legend_html))
        else :
            print("⚠️ Aucune station valide dans la plage d'altitude et de données sélectionnée.")

    display(folium_map)

widgets.interact(update_map, altitude_range=slider_altitude, data_selection=data_selection, month=dropdown, colorbar_checkbox=colorbar_checkbox)

interactive(children=(IntRangeSlider(value=(400, 4000), description='Altitude ≥', max=4000, min=400, step=50),…

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <p><strong>–</strong> La carte ci-dessus permet de sélectionner le <strong>type de données</strong> que l'on souhaite comparer</p>
  <p><strong>–</strong> Nous pouvons choisir une <strong>tranche d'altitude</strong>, pour comparer des valeurs en plaine, en moyenne altitude, ou en montagne</p>
  <p><strong>–</strong> Un bouton nous permet d'<strong>afficher la légende</strong>. Celle-ci comprends :  </p>
    <li><strong></strong><strong>valeur minimum</strong> ainsi que la localité de la station, pour la sélection affichée</li>
    <li><strong></strong><strong>valeur moyenne</strong> pour la sélection affichée</li>
    <li><strong></strong><strong>valeur maximum</strong> ainsi que la localité de la station, pour la sélection affichée</li>
   
  <p><strong>–</strong> Des <strong>pastilles de couleurs</strong> permettent de visualiser l'emplacement des stations de mesure sur la carte. Les couleurs sont dynamique en fonction des valeurs affichées et si l'on clique dessus, un <strong>popup</strong> apparait, contenant : </p>
    <li><strong></strong><strong>Le nom de la localité</strong> où se trouve la station de mesure</li>
    <li><strong></strong><strong>L'altitude</strong> de la station de mesure</li>
    <li><strong></strong><strong>La valeur</strong> mesurée</li>
    <li><strong></strong><strong>Le nombre d'observations</strong> qui est le nombre de mesures effectuées pour le type de valeur, ce qui donne une idée de la pertinence de la valeur. Le chiffre maximal théorique est de 5850, ce qui correspond à une mesure par jour durant 65 ans, mais peut passablement varié, selon le type de valeurs mesurées, telle que la hauteur de neige qui n'est mesurée qu'une partie de l'année. </li>
</div>

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="margin-top: 0;">📊 Etablissement d'une note par station</h2>

  <p><strong>–</strong> En fonction de l'ensoleillement, des précipitation et des températures</p>
  <p><strong>–</strong> Création d'un Dataframe pour ces scores, avec affichage</p>
</div>

In [15]:
# First Step : mean_rows selection (without htoautd0)
mean_cols = [
    col for col in dataWeather_month.columns
    if col.endswith('_mean') and col != 'htoautd0_mean'
]

# Step 2 : Score DataFrame 
scores_df = dataWeather_month[['station_abbr', 'month']].copy()

# Step 3 : Scores calculation from 0 to 10
for col in mean_cols:
    col_min = dataWeather_month[col].min()
    col_max = dataWeather_month[col].max()
    score_col = col.replace('_mean', '_score')

    if col in ['rre150d0_mean', 'fkl010d0_mean']:
        # Inversion : less = better for wind mean and rain mean
        scores_df[score_col] = (1 - (dataWeather_month[col] - col_min) / (col_max - col_min)) * 10
    else:
        # Standard : higher = better for sun and temperature
        scores_df[score_col] = ((dataWeather_month[col] - col_min) / (col_max - col_min)) * 10
    

scores_df = scores_df.round(1)


# List of score's rows to include 
score_cols = [col for col in scores_df.columns if col.endswith('_score')]

# Score's mean
scores_df['overall_rating'] = scores_df[score_cols].mean(axis=1).round(1)

# Non releavant ligne removal
scores_df = scores_df.dropna(subset=score_cols + ['overall_rating']).round(1)


scores_df = scores_df.sort_values(by=['month', 'overall_rating'], ascending=[True, False])

scores_df.groupby('month').first()[['station_abbr',  'overall_rating']]

display(scores_df)

,station_abbr,month,fkl010d0_score,rre150d0_score,sremaxdv_score,tre200d0_score,overall_rating
792,GRO,1,9.9,8.9,7.1,4.3,7.6
1668,VIO,1,7.9,8.8,10.0,3.6,7.6
420,COM,1,9.1,9.1,7.2,4.2,7.4
1236,OTL,1,9.5,8.6,6.8,4.7,7.4
144,BIA,1,8.3,8.5,7.8,4.7,7.3
...,...,...,...,...,...,...,...
1619,TIT,12,2.3,8.6,4.6,1.4,4.2
815,GSB,12,5.2,4.5,4.7,2.1,4.1
335,CHA,12,0.0,7.2,3.2,3.4,3.4
527,DOL,12,1.0,4.8,3.7,3.3,3.2
1415,SAE,12,2.4,3.8,4.3,2.0,3.1

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">
  <p><strong>–</strong> On créé, sur la base du Dataframe avec les scores, un nouveau Dataframe, avec les scores par station et par mois</p>
</div>

In [16]:
scores_month = scores_df[['station_abbr', 'month', 'overall_rating']].copy()

scores_month = scores_month.merge(
    station_identifier[['station_abbr', 'station_name']], 
    on='station_abbr', 
    how='left'  # ou 'inner' si tu veux ignorer les stations non communes
)


display(scores_month)

     station_abbr  month  overall_rating              station_name
0             GRO      1             7.6                     Grono
1             VIO      1             7.6               Vicosoprano
2             COM      1             7.4  Acquarossa / Comprovasco
3             OTL      1             7.4           Locarno / Monti
4             BIA      1             7.3                    Biasca
...           ...    ...             ...                       ...
1411          TIT     12             4.2                    Titlis
1412          GSB     12             4.1   Col du Grand St-Bernard
1413          CHA     12             3.4                 Chasseral
1414          DOL     12             3.2                   La Dôle
1415          SAE     12             3.1                    Säntis

[1416 rows x 4 columns]

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">
  <p><strong>–</strong> On créé, sur la base du Dataframe avec les scores mensuels, un nouveau Dataframe, avec les scores par station et par année</p>
</div>

In [17]:
scores_annuel = (
    scores_month
    .groupby('station_abbr', as_index=False)['overall_rating']
    .mean()
    .round(1)
    .sort_values(by='overall_rating', ascending=False)
)

display(scores_annuel)

    station_abbr  overall_rating
86           PSI             8.2
101          SIO             7.8
51           GRO             7.6
48           GRC             7.5
118          ZER             7.5
..           ...             ...
82           PIL             4.9
33           DOL             4.6
22           CHA             4.6
93           SAE             4.1
107          TIT             3.8

[119 rows x 2 columns]

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">
  <p><strong>–</strong> On créé un nouveau Dataframe pour le top 10 des stations</p>
</div>

In [52]:
# Only select necessaries rows before the groupby
df_subset = scores_df[['station_abbr', 'month', 'overall_rating']]

# Month is used as index, then groupby is on the same rank. This prevents including the grouped rows in the app
temp = (
    df_subset
    .set_index('month')
    .groupby(level=0, group_keys=False)
    .apply(lambda x: x.sort_values(by='overall_rating', ascending=False).head(10))
    .reset_index()  # récupérer 'month' comme colonne
)

# List to store top 10 stations for each month
first10_station_month = temp.merge(
    station_identifier[['station_abbr', 'station_name']], on='station_abbr', how='left'
)

display(first10_station_month)

     month station_abbr  overall_rating              station_name
0        1          GRO             7.6                     Grono
1        1          VIO             7.6               Vicosoprano
2        1          COM             7.4  Acquarossa / Comprovasco
3        1          OTL             7.4           Locarno / Monti
4        1          BIA             7.3                    Biasca
..     ...          ...             ...                       ...
115     12          GRC             7.1                   Grächen
116     12          LUG             7.1                    Lugano
117     12          AND             7.0                    Andeer
118     12          EVO             7.0           Evolène / Villa
119     12          LAT             7.0           Bergün / Latsch

[120 rows x 4 columns]

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">
  <p><strong>–</strong> On créé un nouveau Dataframe pour le top 10 des pires stations</p>
</div>

In [61]:
# Only necessary rows are selected before groupby
df_subset = scores_df[['station_abbr', 'month', 'overall_rating']]

# Month is used as index, then groupby is on the same rank. This prevents including the grouped rows in the app
temp = (
    df_subset
    .set_index('month')
    .groupby(level=0, group_keys=False)
    .apply(lambda x: x.sort_values(by='overall_rating', ascending=True).head(10))
    .reset_index()  # récupérer 'month' comme colonne
)

# List to store last 10 stations for each month
last10_station_month = temp.merge(
    station_identifier[['station_abbr', 'station_name']], on='station_abbr', how='left'
)

display(last10_station_month)

     month station_abbr  overall_rating             station_name
0        1          TIT             2.2                   Titlis
1        1          SAE             3.2                   Säntis
2        1          DOL             3.4                  La Dôle
3        1          CHA             3.6                Chasseral
4        1          GSB             4.2  Col du Grand St-Bernard
..     ...          ...             ...                      ...
115     12          PIL             4.3                  Pilatus
116     12          GRH             4.4           Grimsel Hospiz
117     12          GUE             4.7        Gütsch, Andermatt
118     12          HOE             5.0                   Hörnli
119     12          MLS             5.0               Le Moléson

[120 rows x 4 columns]

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">
  <p><strong>–</strong> On créé un nouveau Dataframe pour le top 10 des stations par année</p>
</div>

In [54]:
first10_stations_year = scores_annuel.head(10).reset_index(drop=True)

first10_stations_year = first10_stations_year.merge(
    station_identifier[['station_abbr', 'station_name']], 
    on='station_abbr', 
    how='left'  
)

display(first10_stations_year)

  station_abbr  overall_rating       station_name
0          PSI             8.2  Würenlingen / PSI
1          SIO             7.8               Sion
2          GRO             7.6              Grono
3          GRC             7.5            Grächen
4          ZER             7.5            Zermatt
5          EVO             7.4    Evolène / Villa
6          AND             7.4             Andeer
7          VIS             7.4               Visp
8          MTE             7.3             Mottec
9          LAT             7.3    Bergün / Latsch

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">
  <p><strong>–</strong> On créé un nouveau Dataframe pour le top 10 des pires stations par année</p>
</div>

In [55]:
last10_stations_year = scores_annuel.tail(10).iloc[::-1].reset_index(drop=True)
last10_stations_year = last10_stations_year.merge(
    station_identifier[['station_abbr', 'station_name']],
    on='station_abbr',
    how='left'
)

display(last10_stations_year)

  station_abbr  overall_rating             station_name
0          TIT             3.8                   Titlis
1          SAE             4.1                   Säntis
2          CHA             4.6                Chasseral
3          DOL             4.6                  La Dôle
4          PIL             4.9                  Pilatus
5          GSB             4.9  Col du Grand St-Bernard
6          GRH             5.2           Grimsel Hospiz
7          GUE             5.2        Gütsch, Andermatt
8          WFJ             5.4            Weissfluhjoch
9          PMA             5.5            Piz Martegnas

<div style="background-color: #e0f7fa; color: #004d40; padding: 20px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="margin-top: 0;">🏆 Graphiques et cartes pour le ranking des régions</h2>

  <p><strong>–</strong> On importe les dépendances nécessaires</p>
  <p><strong>–</strong> On déploie les Widgets et on appelle les Dataframes crées ci-dessus</p>
</div>

In [56]:
from IPython.display import display, clear_output
import matplotlib.pyplot as plt
import ipywidgets as widgets
import folium
from folium.plugins import MarkerCluster

In [57]:
def configurerStyleGraphic():
    import matplotlib.pyplot as plt
    #Emoji 🏔️☀️📅 setup
    plt.rcParams.update({
        'font.family': 'Segoe UI Emoji',   
        'axes.titlesize': 14,
        'axes.labelsize': 12,
        'xtick.labelsize': 10,
        'ytick.labelsize': 10,
        'figure.facecolor': 'white',
        'axes.edgecolor': 'gray',
        'axes.grid': True,
        'grid.alpha': 0.3,
        'grid.linestyle': '--',
    })

In [68]:
# Dropdown menu to change scale repartition between map and graph
split_dropdown = widgets.Dropdown(
    options=[
        ("50% / 50%", (50, 50)),
        ("60% / 40%", (60, 40)),
        ("70% / 30%", (70, 30)),
        ("40% / 60%", (40, 60))
    ],
    value=(50, 50),
    description="Répartition:"
)


selection_mode = widgets.Dropdown(
    options=["Annuel les 10 premiers",
             "Annuel les 10 derniers",
             "Mois les 10 premiers",
             "Mois les 10 derniers"],
    description="Affichage :"
)

selection_month = widgets.Dropdown(
    options=[(month, num) for (month, num) in months_labels],
    value=1,
    description='Mois :'
)

# Output for maps and history graph
output_map = widgets.Output()
output_plot = widgets.Output()

# update layouts regarding user selections
def update_layout(change):
    left, right = change['new']
    output_map.layout = widgets.Layout(width=f"{left}%")
    output_plot.layout = widgets.Layout(width=f"{right}%")

split_dropdown.observe(update_layout, names='value')

def updateVisibilityMnth(mode):
    if mode == "Annuel les 10 premiers" or mode == "Annuel les 10 derniers":
        selection_month.layout.display = 'none'
    else:
        selection_month.layout.display = ''

def getTilesMonth(month):
    if month in [3, 4, 5]:     # Spring
        return 'Stamen TonerLite'
    elif month in [6, 7, 8]:   # Summer
        return 'CartoDB Positron'
    elif month in [9, 10, 11]: # Autumn
        return 'Stamen Terrain'
    else:                      # Winter
        return 'Stamen Toner'

selection_mode.observe(lambda change: updateVisibilityMnth(change['new']), names='value')
updateVisibilityMnth(selection_mode.value)

#Dropdown's container for mode and month selection
controls = widgets.HBox([selection_mode, selection_month])
# Global container for controls : split_dropdown on top of the others
all_controls = widgets.VBox([split_dropdown, controls])
all_controls.layout = widgets.Layout(margin='0 0 15px 0')


try:
    unit_rainfall = columns_identifier.loc[
        columns_identifier['parameter_shortname'] == 'rre150d0', 'parameter_unit'
    ].values[0]
except IndexError:
    unit_rainfall = ""  

try:
    unit_sunshine = columns_identifier.loc[
        columns_identifier['parameter_shortname'] == 'sremaxdv', 'parameter_unit'
    ].values[0]
except IndexError:
    unit_sunshine = "" 

try:
    unit_snow_height = columns_identifier.loc[
        columns_identifier['parameter_shortname'] == 'htoautd0', 'parameter_unit'
    ].values[0]
except IndexError:
    unit_snow_height = ""  



# Fusion function
def displayTop10Fusion(mode, month):
    with output_map:
        clear_output(wait=True)
        configurerStyleGraphic()

        colorBar = 'mediumseagreen'

        if mode == "Annuel les 10 premiers":
            df = first10_stations_year.copy()
            df['month'] = 1
            df_value = dataWeather_month.copy()
            colorBar = 'mediumseagreen'
        elif mode == "Annuel les 10 derniers":
            df = last10_stations_year.copy()
            df['month'] = 1
            df_value = dataWeather_month.copy()
            colorBar = 'cornflowerblue'
        else:
            if mode == "Mois les 10 premiers":
                df = first10_station_month[first10_station_month['month'] == month].sort_values(
                    by='overall_rating', ascending=False).head(10)
                df_value = dataWeather_year.copy()
                colorBar = 'seagreen'
            else:
                df = last10_station_month[last10_station_month['month'] == month].sort_values(
                    by='overall_rating', ascending=True).head(10)
                df_value = dataWeather_year.copy()
                colorBar = 'royalblue'

        tile = getTilesMonth(month if mode == "Top 10 par mois" else 1)

        folium_map = folium.Map(location=[46.8, 8.3], zoom_start=8, width='80%', height='80%')
        popup = folium.Popup("Contenu du popup", max_width=800)

        cluster = MarkerCluster().add_to(folium_map)

        for _, station in station_identifier.iterrows():
            abbr = station['station_abbr']
            match = df[df['station_abbr'] == abbr]
            match_val = df_value[df_value['station_abbr'] == abbr]

            

            if not match.empty:
                note = match.iloc[0]['overall_rating']
                name = match.iloc[0]['station_name']
                rain = match_val.iloc[0].get('rre150d0_mean', 0)
                sun = match_val.iloc[0].get('sremaxdv_mean', 0)
                snow = match_val.iloc[0].get('htoautd0_mean', 0)
                lat = station['station_coordinates_wgs84_lat']
                lon = station['station_coordinates_wgs84_lon']

                # 🧾 popup setup
                html_popup = f"""
                <div style='font-family: Arial; font-size: 13px;'>
                    <b style='font-size: 15px;'>{name}</b><br>
                    ☀️ Soleil : {sun:.1f} [{unit_sunshine}]<br>
                    🌧️ Pluie : {rain:.1f} [{unit_rainfall}]<br>
                    ❄️ Neige : {snow:.1f} [{unit_snow_height}]<br>
                    📈 Note : <b>{note}</b>
                    </div>
                """

                iframe = IFrame(html=html_popup, width=200, height=120)
                popup = Popup(iframe, max_width=200)

                folium.CircleMarker(
                    location=[lat, lon],
                    radius=8,
                    color='darkgreen' if note >= 8.5 else 'orange' if note >= 7 else 'red',
                    fill=True,
                    fill_opacity=0.8,
                    tooltip=name,
                    popup=popup
                ).add_to(cluster)

        display(folium_map)

    with output_plot:
        clear_output(wait=True)
        plt.figure(figsize=(8, 5))
        plt.rcParams['font.family'] = 'Segoe UI Emoji'

        if  "Annuel" in mode:
            plt.barh(df['station_name'], df['overall_rating'], color=colorBar)
            plt.xlabel("Note annuelle")
            plt.title("🏆 Top 10 des stations sur l’année")
        else:
            plt.barh(df['station_name'], df['overall_rating'], color=colorBar)
            month_name = months_labels[month - 1][0]
            plt.xlabel("Note mensuelle")
            plt.title(f"📅 Top 10 des stations en {month_name}")

        plt.gca().invert_yaxis()
        plt.grid(axis='x', linestyle='--', alpha=0.4)
        plt.tight_layout()
        plt.show()


selection_mode.observe(lambda change: updateVisibilityMnth(change['new']), names='value')
updateVisibilityMnth(selection_mode.value)

# Interactive_output used to connect the fonction to specifics controls
interactive_out = widgets.interactive_output(displayTop10Fusion, {'mode': selection_mode, 'month': selection_month})

# Final organisation : controls on top, then map and graph output
fusion_layout = widgets.HBox([output_map, output_plot])
global_layout = widgets.VBox([all_controls, fusion_layout, interactive_out])

display(global_layout)

VBox(children=(VBox(children=(Dropdown(description='Répartition:', options=(('50% / 50%', (50, 50)), ('60% / 4…

<div style="background-color: #e0f7fa; color: #004d40; padding: 25px; max-width: 95%; border-radius: 10px; font-family: Arial, sans-serif; margin: auto;">

  <h2 style="color: #9b4d00;">🚧 Problèmes rencontrés</h2>
  <ol style="line-height: 1.8;">
    <li><strong>Recherche de données</strong>: La collecte de données a été compliquée. Finalement, le volume récupéré étant conséquent, un tri a du être effectué.</li>
    <li><strong>Que faire de ces données</strong> : Pas facile de trouver un but, ni de trouver une corrélation directe entre les types de valeurs obtenus.</li>
    <li><strong>Mise à jour et rendu</strong>: parfois pas facile d'avoir un résultat correct à différents endroits.</li>
    <li><strong>Justesse des données</strong> : est-ce que les manupilations et calculs effectués donnent 100 % de réponses correctes ? Il nous faudrait plus de temps pour vérifier.</li>
    
  </ol>

  <h2 style="color: #9b4d00;">🐞 Bugs connus </h2>
  <ol style="line-height: 1.8;">
  <li><strong>Recherche de données</strong>: La collecte de données a été compliquée. Finalement, le volume récupéré étant conséquent, un tri a du être effectué.</li>
    <li><strong>Que faire de ces données</strong> : Pas facile de trouver un but.</li>
    <li><strong>Mise à jour et rendu</strong>: parfois pas facile d'avoir un résultat correct à différents endroits.</li>
    <li><strong>Justesse des données</strong> : est-ce que les manipulations et calculs effectués donnent 100 % de réponses correctes ? Il nous faudrait plus de temps pour vérifier.</li>
  </ol  >
      <h2 style="color: #9b4d00;">🎯 Conclusion </h2>
  <p>
    Les objectifs de notre projet était d'une part de permettre de <strong>visualiser certaines données</strong> qu'il n'est pas possible d'intellectualiser. La première carte permet cette approche personnalisée qui laisse à l'utilisateur la possibilité de "jouer" avec l'affichage des informations. 
    Le second objectif, bien plus important à nos yeux, était de pouvoir définir <strong>quelle région de suisse était la plus agréabe à vivre</strong> d'un point de vue météorologique. Sur ce point, le constat est un peu amer pour le résident broyard, qui doit bien admettre que sa région peine à faire bonne figure face à son rival de toujours, le valaisan.</p>

  <p>
    Il est toutefois intéressant de constater que malgré nos idées préconçues, bien que très bien représentés dans le top 10 des meilleurs endroits pour vivre en Suisse, aucune des stations de mesures de la vallée du Rhône valaisanne et ni même celles du Tessin n'occupent la première place de notre classement. Cette première place est occupée par une commune du canton d'Argovie dans le nord de la Suisse, soit dans la localité de Würenlingen. Cette dernière remporte le meilleur score, considérant le meilleur rapport entre un bon ensoleillement, la clémence des températures, une exposition modérée aux vents, ainsi que de faibles précipitations, et ce sur un calcul incluant les valeurs des 65 dernières années. <p> 
  <p> 
    Il est toutefois opportun de noter que l'emplacement du lieu le plus agréable à vivre varie fortement, d'un mois à l'autre. Si les cantons du Tessin et du Valais tirent leur épingle du jeux pendant la saison hivernale, ils quittent le podium au profit d'autres régions de Suisse pendant le reste de l'année. </p>
  </div>